#!/usr/bin/env bash

ops=("Screen Saver" "Lock" "Logout" "Suspend" "Reboot" "Poweroff")
options="$(printf "%s\n" "${ops[@]}")"

chosen="$(echo -e "$options" | rofi -lines 6 -dmenu -p "Power" -width 15 -hide-scrollbar -line-padding 4 -padding 20 -i)"
case $chosen in
"${ops[0]}")
    xdg-screensaver activate
    ;;
"${ops[1]}")
    xdg-screensaver lock
    ;;
"${ops[2]}")
    gnome-session-quit --logout --no-prompt
    ;;
"${ops[3]}")
    systemctl suspend
    ;;
"${ops[5]}")
    systemctl reboot
    ;;
"${ops[6]}")
    systemctl poweroff
    ;;
esac
