#!/usr/bin/env bash

ops=("Screen Saver" "Lock" "Logout" "Suspend" "Reboot" "Poweroff")
options="$(printf "%s\n" "${ops[@]}")"

chosen="$(echo -e "$options" | rofi -lines 6 -dmenu -p "Power" -width 15 -hide-scrollbar -line-padding 4 -padding 20 -i)"
case $chosen in
    "${ops[0]}")
        xdg-screensaver activate
        ;;
    "${ops[1]}")
        xdg-screensaver lock
        ;;
    "${ops[2]}")
        if pgrep -x "i3" >/dev/null; then
            i3-msg exit
        else
            gnome-session-quit --logout --no-prompt
        fi
        ;;
    "${ops[3]}")
        systemctl suspend
        ;;
    "${ops[4]}")
        systemctl reboot
        ;;
    "${ops[5]}")
        systemctl poweroff
        ;;
    *) ;;
esac
