#!/usr/bin/env bash

declare -a packages=(
    "autopep8"
    "bandit"
    "black"
    "docopt"
    "flake8"
    "isort"
    "mypy"
    "pre-commit"
    "pydocstyle"
    "pyls-isort"
    "pylsp-rope"
    "python-lsp-black"
    "python-lsp-server[all]"
)

install() {
    for i in "${packages[@]}"; do
        pip install "$i"
    done
}

while test $# -gt 0; do
    case "$1" in
    -h | --help)
        echo "$package - Lists and optionally install frequently used python packages"
        echo "Options:"
        echo "-h, --help        show brief help"
        echo "-i, --install     Install packages"
        break
        ;;
    -i | --install)
        shift
        install
        break
        ;;
    esac
done

for i in "${packages[@]}"; do
    echo "$i"
done
