#!/usr/bin/env python3
"""
Rename many files sequentially easily.

Usage:
    rename_seq [DIR] [options]

Options:
    -h, --help               Show this help.
    -V, --version            Show version info.
"""
from pathlib import Path

from docopt import docopt

EXTENSIONS = (
    "jpg",
    "png",
    "mp4",
    "m4v",
    "mov",
    "webm",
    "wmv",
    "flv",
    "gif",
)


def lowercase_files(base_dir: Path):
    """Lowercase all filenames in base_dir."""
    for i in base_dir.glob("*"):
        if i.is_file():
            i.rename(Path(i.parent, str(i.name).lower()))


def clean_jpgs(base_dir: Path):
    """Ensure all JPG files are .JPG."""
    for i in base_dir.glob("*.jpeg"):
        i.rename(Path(i.parent, f"{i.stem}.jpg"))


def rename(base_dir: Path):
    """Rename files numerically, from 0 - N, by file extension."""
    index = 0
    for ext in EXTENSIONS:
        for i in base_dir.glob(f"*.{ext}"):
            new = Path(i.parent, f"{index}.{ext}")
            i.rename(new)
            index += 1


if __name__ == "__main__":
    args = docopt(__doc__)
    if args["DIR"] is None:
        args["DIR"] = Path(".")

    base_dir = Path(args["DIR"])

    lowercase_files(base_dir)
    clean_jpgs(base_dir)
    rename(base_dir)
