require "user.launch"
require "user.options"
require "user.keymaps"
require "user.autocmds"

spec "user.alpha"
spec "user.autopairs"
spec "user.cmp"
spec "user.colorscheme"
spec "user.comment"
spec "user.devicons"
spec "user.gitsigns"
spec "user.harpoon"
spec "user.illuminate"
spec "user.indentline"
spec "user.lspconfig"
spec "user.lualine"
spec "user.mason"
spec "user.navic"
spec "user.neogit"
spec "user.oil"
spec "user.project"
spec "user.schemastore"
spec "user.telescope"
spec "user.treesitter"
spec "user.whichkey"

spec "user.bqf"

require "user.lazy"
